/* this code was generated by automated tool,
   should not edit by hand */

export interface HelloService {
  SayHello(request: _): Message;
  GetProducts(request: _): Products;
}

export interface _ {}

export interface Message {
  message?: string;
}

export interface Product {
  id?: number;
  name?: string;
  description?: string;
}

export interface Products {
  products?: Product[];
}
